Pequenas correções nos textos
tecMTST/caso-de-policia pull request #2
Opened 2024-10-21 17:15 UTC by PabloRMelo

Correções em notícias e sugestões.

2024-10-21 19:35 UTC, nawarian requested changes

2024-10-21 19:35 UTC, nawarian commented on assets/dados/noticias.csv
> +Roubos pelo PCC estranhamente diminuíram na capital esta semana.;18
Remover o ponto final

2024-10-21 19:35 UTC, nawarian commented on assets/dados/noticias.csv
> +A maior queda na porcentagem de violência doméstica ocorre em São Paulo, diz persquisa;6
Typo: pesquisa vs. persquisa

2024-10-21 19:35 UTC, nawarian commented on assets/dados/noticias.csv
> +Furtos e brigas são cada vez mais difíceis de se ver na Cracolândia após ação social do governo ;11
Remover espaço antes do ponto e vírgula

2024-10-21 19:35 UTC, nawarian commented on assets/dados/noticias.csv
> +O novo treinamento para os agentes diminui as abordagens violentas e o estresse em momentos de conflito, diz especialista ;3
Talvez "diminuiu" em vez de "diminui"

2024-10-21 19:35 UTC, nawarian commented on assets/dados/sugestoes.csv
> +2;Douces;Investigar 3 lojas de revenda de celulares.;5;-5;10
A gente poderia remover o número 3 daqui. Havia colocado quando fazia sentido repetir as propostas. Mas agora é só um número arbitrário que não comunica muito bem a intenção.

2024-10-21 19:35 UTC, nawarian commented on assets/dados/sugestoes.csv
>  ﻿Id;Conselheiro;Texto;Custo;Criminalidade;Popularidade
Isa fez um trabalho de colocar as sugestões do Lurdes no infinitivo. Vale a pena fazer o mesmo com as sugestões do Boulos?

2024-10-21 19:46 UTC, PabloRMelo commented on assets/dados/noticias.csv
> +Roubos pelo PCC estranhamente diminuíram na capital esta semana.;18
arrumado

2024-10-21 19:46 UTC, PabloRMelo commented on assets/dados/noticias.csv
> +A maior queda na porcentagem de violência doméstica ocorre em São Paulo, diz persquisa;6
arrumado

2024-10-21 19:46 UTC, PabloRMelo commented on assets/dados/noticias.csv
> +Furtos e brigas são cada vez mais difíceis de se ver na Cracolândia após ação social do governo ;11
arrumado

2024-10-21 19:49 UTC, PabloRMelo commented on assets/dados/sugestoes.csv
>  ﻿Id;Conselheiro;Texto;Custo;Criminalidade;Popularidade
Todas estão no infinitivo

2024-10-22 07:45 UTC, nawarian requested changes
Tudo certo, precisa remover só um errinho e marcha!

2024-10-22 07:45 UTC, nawarian commented on assets/dados/noticias.csv
> +“Antes eu estava num inferno. No Caps, me disseram que eu podia ver uma saída. Aqui você encontra o amor que ninguém dá”, diz paciente”;2
Tem uma aspa extra ao final da frase

2024-10-22 07:58 UTC, nawarian approved these changes

2024-10-22 07:58 UTC, merged